name 'blp-grub'
version '1.0.1'
maintainer 'Bloomberg Finance L.P.'
maintainer_email 'chef@bloomberg.net'
license 'Apache-2.0'
description 'Configures grub'
long_description 'Configures grub'

issues_url 'https://github.com/bloomberg-cookbooks/grub/issues'
source_url 'https://github.com/bloomberg-cookbooks/grub'
chef_version '>= 12.5'

supports 'centos', '>= 6.0'
supports 'redhat', '>= 6.0'
supports 'ubuntu', '>= 12.04'
